### ISSUE TITLE
Set up new Angular app for a new documentation site

### ISSUE THREAD

**Issue by benjamincharity** [GetTerminus/terminus-ui#1443]
- [x] Initialize new app with SCSS styles using the Angular CLI
- [x] Set up router for lazy loaded routes (all routes should be lazy loaded)
- [x] Create shared module
  - [x] Import all UI modules to shared module (this is a good opportunity to verify our install docs are still up to date)
- [x] Convert testing to Jest
- [x] Push to new repo https://github.com/GetTerminus/ui-docs-site

**Comment by shani-terminus** [comment]
There was a lot of copy/pasting/refactoring. It's not super-refined, but marks the checkboxes.
I put in the linters and added the cm script, but haven't updated the scripts in package.json
Currently going to port 4201, so it can run at the same time as the library.

As far as our install docs, the only thing missing was material. I know we're trying to move away from it, so you can decide the best course of action.

Since there's nothing to compare against, there's no PR, but the code is up: https://github.com/GetTerminus/ui-docs-site
