### ISSUE TITLE
Button component to have the ability to provide different variant types similar to angular material

### ISSUE THREAD

**Issue by divyameher** [GetTerminus/terminus-ui#704]
Can we customize button component to have the ability to provide different variant types - `mat-button`, `mat-fab`, `mat-mini-fab `& `mat-icon-button` along with `mat-raised-button`?

**Comment by benjamincharity** [comment]
I'm not sure that we will support this. While we are using Material as a springboard so that we aren't forced to create everything from the ground up, the goal of this library isn't to fully wrap the Material library. The ultimate goal is to `Create a UI library that speeds up the Terminus development process while only providing choices that follow the Terminus design language`.

This is why our current button implementation is so specific (rather than just wrapping all Material button types). We can't solve for everyone while constraining our own team.

That being said, we did open source this for a reason. We want to be open and transparent with this process and hopefully give back in the way of exposing our solutions. Beyond that, I personally would love to see some pieces of this library extracted out for general use. (like our responsive navigation or paginator)

**Comment by divyameher** [comment]
That's fine.Thank You :)
