### ISSUE TITLE
ts-icon not supporting custom svg icons

### ISSUE THREAD

**Issue by vinayns93** [GetTerminus/terminus-ui#831]
When using the custom svg icons like `<ts-icon svgIcon="left-arrow"></ts-icon>`

Following is shown in the console - Error retrieving icon: Unable to find icon with the name ":svgIcon"

Issue recreated here: https://terminus-ui-demos-vkf6ba.stackblitz.io/components/icon

**Comment by benjamincharity** [comment]
Hey @vinayns93, thanks for calling this out.

Looking into custom SVGs, I don't believe we will support this moving forward. This feature of `mat-icon` provides an easy way for specific components or modules to dynamically register and use new icons. Since the specific use-case of this library is to enforce a consistent design language across all of our modules and application this would be an anti-feature of sorts.

If a new icon is needed, we should have the full buy-in from design/ux and the icon should be added to the set provided by this library.

---

That all being said, I definitely understand the need for custom SVG icons in most projects. Luckily the `MatIconModule` offers the full feature set. I would suggest using that directly. Since this library is built on Material it will integrate smoothly.

https://material.angular.io/components/icon

**Comment by divyameher** [comment]
@benjamincharity When I created my custom icon component by wrapping `mat-icon`, removing this line of code https://github.com/GetTerminus/terminus-ui/blob/15ec49b31231a8ad249ad96a206e67678a3ee2fc/terminus-ui/src/icon/icon.component.html#L16 in template provides facility to render registered svg icons inside custom icon component with `MatIconRegistry`. Similarly I feel this fix may address above issue

**Comment by vinayns93** [comment]
@divyameher Thank you. This worked for me.

**Comment by benjamincharity** [comment]
Thanks for posting your solution @divyameher! 🙏 

Very glad this library is providing some value to people outside our org!

Out of pure curiosity, any specific reason you are both using this library over the pure Angular Material library?
